[application]

# App (Project) Name
name = "Roller"

# Set the out_dir as documented in https://dioxuslabs.com/learn/0.6/cookbook/publishing
# This still includes the extra "public" folder, so this is not used, and instead the content is copied from its default location.
# out_dir = "../docs"

[web.app]

# HTML title tag content
title = "Roller"

# This is needed if not using custom domain:
# base_path = "game-tools"

# include `assets` in web platform
[web.resource]

# Additional CSS style files
style = []

# Additional JavaScript files
script = []

[web.resource.dev]

# Javascript code file
# serve: [dev-server] only
script = []
